#ifndef _LEVEL_H
#define _LEVEL_H

enum ActId  {
    ACT_1 = 0,
    ACT_2,
    ACT_3,
    ACT_4,
    ACT_5
};
typedef enum ActId  ActId;


enum WaypointId {
    NO_WAYPOINT = 0xff,
    WP_ROGUE_ENCAMPMENT = 0,
    WP_COLD_PLAINS,
    WP_STONY_FIELD,
    WP_DARK_WOOD,
    WP_BLACK_MARSH,
    WP_OUTER_CLOISTER,
    WP_JAIL_LEVEL_1,
    WP_INNER_CLOISTER,
    WP_CATACOMBS_LEVEL_2,
    WP_LUT_GHOLEIN,
    WP_SEWERS_LEVEL_2,
    WP_DRY_HILLS,
    WP_HALLS_OF_THE_DEAD_LEVEL_2,
    WP_FAR_OASIS,
    WP_LOST_CITY,
    WP_PALACE_CELLAR_LEVEL_1,
    WP_ARCANE_SANCTUARY,
    WP_CANYON_OF_THE_MAGI,
    WP_KURAST_DOCKTOWN,
    WP_SPIDER_FOREST,
    WP_GREAT_MARSH,
    WP_FLAYER_JUNGLE,
    WP_LOWER_KURAST,
    WP_KURAST_BAZAAR,
    WP_UPPER_KURAST,
    WP_TRAVINCAL,
    WP_DURANCE_OF_HATE_LEVEL_2,
    WP_THE_PANDEMONIUM_FORTRESS,
    WP_CITY_OF_THE_DAMNED,
    WP_RIVER_OF_FLAME,
    WP_HARROGATH,
    WP_FRIGID_HIGHLANDS,
    WP_ARREAT_PLATEAU,
    WP_CRYSTALLINE_PASSAGE,
    WP_GLACIAL_TRAIL,
    WP_HALLS_OF_PAIN,
    WP_FROZEN_TUNDRA,
    WP_THE_ANCIENTS_WAY,
    WP_THE_WORLDSTONE_KEEP_LEVEL_2
};
typedef enum WaypointId  WaypointId;


enum LevelId {
    NO_LEVEL = 0,
    ROGUE_ENCAMPMENT,
    BLOOD_MOOR,
    COLD_PLAINS,
    STONY_FIELD,
    DARK_WOOD,
    BLACK_MARSH,
    TAMOE_HIGHLAND,
    DEN_OF_EVIL,
    CAVE_LEVEL_1,
    UNDERGROUND_PASSAGE_LEVEL_1,
    HOLE_LEVEL_1,
    PIT_LEVEL_1,
    CAVE_LEVEL_2,
    UNDERGROUND_PASSAGE_LEVEL_2,
    HOLE_LEVEL_2,
    PIT_LEVEL_2,
    BURIAL_GROUNDS,
    CRYPT,
    MAUSOLEUM,
    FORGOTTEN_TOWER,
    TOWER_CELLAR_LEVEL_1,
    TOWER_CELLAR_LEVEL_2,
    TOWER_CELLAR_LEVEL_3,
    TOWER_CELLAR_LEVEL_4,
    TOWER_CELLAR_LEVEL_5,
    MONASTERY_GATE,
    OUTER_CLOISTER,
    BARRACKS,
    JAIL_LEVEL_1,
    JAIL_LEVEL_2,
    JAIL_LEVEL_3,
    INNER_CLOISTER,
    CATHEDRAL,
    CATACOMBS_LEVEL_1,
    CATACOMBS_LEVEL_2,
    CATACOMBS_LEVEL_3,
    CATACOMBS_LEVEL_4,
    TRISTRAM,
    MOO_MOO_FARM,
    LUT_GHOLEIN,
    ROCKY_WASTE,
    DRY_HILLS,
    FAR_OASIS,
    LOST_CITY,
    VALLEY_OF_SNAKES,
    CANYON_OF_THE_MAGI,
    SEWERS_ACT_2_LEVEL_1,
    SEWERS_ACT_2_LEVEL_2,
    SEWERS_ACT_2_LEVEL_3,
    HAREM_LEVEL_1,
    HAREM_LEVEL_2,
    PALACE_CELLAR_LEVEL_1,
    PALACE_CELLAR_LEVEL_2,
    PALACE_CELLAR_LEVEL_3,
    STONY_TOMB_LEVEL_1,
    HALLS_OF_THE_DEAD_LEVEL_1,
    HALLS_OF_THE_DEAD_LEVEL_2,
    CLAW_VIPER_TEMPLE_LEVEL_1,
    STONY_TOMB_LEVEL_2,
    HALLS_OF_THE_DEAD_LEVEL_3,
    CLAW_VIPER_TEMPLE_LEVEL_2,
    MAGGOT_LAIR_LEVEL_1,
    MAGGOT_LAIR_LEVEL_2,
    MAGGOT_LAIR_LEVEL_3,
    ANCIENT_TUNNELS,
    TAL_RASHAS_TOMB_1,
    TAL_RASHAS_TOMB_2,
    TAL_RASHAS_TOMB_3,
    TAL_RASHAS_TOMB_4,
    TAL_RASHAS_TOMB_5,
    TAL_RASHAS_TOMB_6,
    TAL_RASHAS_TOMB_7,
    DURIELS_LAIR,
    ARCANE_SANCTUARY,
    KURAST_DOCKTOWN,
    SPIDER_FOREST,
    GREAT_MARSH,
    FLAYER_JUNGLE,
    LOWER_KURAST,
    KURAST_BAZAAR,
    UPPER_KURAST,
    KURAST_CAUSEWAY,
    TRAVINCAL,
    ARACHNID_LAIR,
    SPIDER_CAVERN,
    SWAMPY_PIT_LEVEL_1,
    SWAMPY_PIT_LEVEL_2,
    FLAYER_DUNGEON_LEVEL_1,
    FLAYER_DUNGEON_LEVEL_2,
    SWAMPY_PIT_LEVEL_3,
    FLAYER_DUNGEON_LEVEL_3,
    SEWERS_ACT_3_LEVEL_1,
    SEWERS_LEVEL_2,
    RUINED_TEMPLE,
    DISUSED_FANE,
    FORGOTTEN_RELIQUARY,
    FORGOTTEN_TEMPLE,
    RUINED_FANE,
    DISUSED_RELIQUARY,
    DURANCE_OF_HATE_LEVEL_1,
    DURANCE_OF_HATE_LEVEL_2,
    DURANCE_OF_HATE_LEVEL_3,
    THE_PANDEMONIUM_FORTRESS,
    OUTER_STEPPES,
    PLAINS_OF_DESPAIR,
    CITY_OF_THE_DAMNED,
    RIVER_OF_FLAME,
    THE_CHAOS_SANCTUARY,
    HARROGATH,
    BLOODY_FOOTHILLS,
    FRIGID_HIGHLANDS,
    ARREAT_PLATEAU,
    CRYSTALLINE_PASSAGE,
    FROZEN_RIVER,
    GLACIAL_TRAIL,
    DRIFTER_CAVERN,
    FROZEN_TUNDRA,
    THE_ANCIENTS_WAY,
    ICY_CELLAR,
    ARREAT_SUMMIT,
    NIHLATHAKS_TEMPLE,
    HALLS_OF_ANGUISH,
    HALLS_OF_PAIN,
    HALLS_OF_VAUGHT,
    ABADDON,
    PIT_OF_ACHERON,
    INFERNAL_PIT,
    THE_WORLDSTONE_KEEP_LEVEL_1,
    THE_WORLDSTONE_KEEP_LEVEL_2,
    THE_WORLDSTONE_KEEP_LEVEL_3,
    THRONE_OF_DESTRUCTION,
    THE_WORLDSTONE_CHAMBER,
    MATRONS_DEN,
    FORGOTTEN_SANDS,
    FURNACE_OF_PAIN,
    UBER_TRISTRAM
};
typedef enum LevelId  LevelId;


#define MAX_ACT 5
#define MAX_ACT_NAME 8
#define MAX_ACT_WP 9

struct ActInfo {
    ActId id;
    char name[MAX_ACT_NAME];
    LevelId wp[MAX_ACT_WP];
};
typedef struct ActInfo  ActInfo;

extern const ActInfo ACT_INFO[MAX_ACT];


#define MAX_LEVEL 137
#define MAX_LEVEL_NAME 32

struct LevelInfo {
    LevelId id;
    char name[MAX_LEVEL_NAME];
    ActId act;
    WaypointId wp;
};
typedef struct LevelInfo  LevelInfo;

extern const LevelInfo LEVEL_INFO[MAX_LEVEL];


#endif
