#include "sdk/level.h"

const ActInfo ACT_INFO[MAX_ACT] = {
    {.name="Act I", .wp={
        ROGUE_ENCAMPMENT,
        COLD_PLAINS,
        STONY_FIELD,
        DARK_WOOD,
        BLACK_MARSH,
        OUTER_CLOISTER,
        JAIL_LEVEL_1,
        INNER_CLOISTER,
        CATACOMBS_LEVEL_2
    }},
    {.name="Act II", .wp={
        LUT_GHOLEIN,
        SEWERS_LEVEL_2,
        DRY_HILLS,
        HALLS_OF_THE_DEAD_LEVEL_2,
        FAR_OASIS,
        LOST_CITY,
        PALACE_CELLAR_LEVEL_1,
        ARCANE_SANCTUARY,
        CANYON_OF_THE_MAGI
    }},
    {.name="Act III", .wp={
        KURAST_DOCKTOWN,
        SPIDER_FOREST,
        GREAT_MARSH,
        FLAYER_JUNGLE,
        LOWER_KURAST,
        KURAST_BAZAAR,
        UPPER_KURAST,
        TRAVINCAL,
        DURANCE_OF_HATE_LEVEL_2
    }},
    {.name="Act IV", .wp={
        THE_PANDEMONIUM_FORTRESS,
        CITY_OF_THE_DAMNED,
        RIVER_OF_FLAME
    }},
    {.name="Act V", .wp={
        HARROGATH,
        FRIGID_HIGHLANDS,
        ARREAT_PLATEAU,
        CRYSTALLINE_PASSAGE,
        GLACIAL_TRAIL,
        HALLS_OF_PAIN,
        FROZEN_TUNDRA,
        THE_ANCIENTS_WAY,
        THE_WORLDSTONE_KEEP_LEVEL_2
    }}
};


const LevelInfo LEVEL_INFO[MAX_LEVEL] = {
    {.name="Null",                        .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Rogue Encampment",            .act=ACT_1, .wp=WP_ROGUE_ENCAMPMENT},
    {.name="Blood Moor",                  .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Cold Plains",                 .act=ACT_1, .wp=WP_COLD_PLAINS},
    {.name="Stony Field",                 .act=ACT_1, .wp=WP_STONY_FIELD},
    {.name="Dark Wood",                   .act=ACT_1, .wp=WP_DARK_WOOD},
    {.name="Black Marsh",                 .act=ACT_1, .wp=WP_BLACK_MARSH},
    {.name="Tamoe Highland",              .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Den of Evil",                 .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Cave Level 1",                .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Underground Passage Level 1", .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Hole Level 1",                .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Pit Level 1",                 .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Cave Level 2",                .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Underground Passage Level 2", .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Hole Level 2",                .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Pit Level 2",                 .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Burial Grounds",              .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Crypt",                       .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Mausoleum",                   .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Forgotten Tower",             .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Tower Cellar Level 1",        .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Tower Cellar Level 2",        .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Tower Cellar Level 3",        .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Tower Cellar Level 4",        .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Tower Cellar Level 5",        .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Monastery Gate",              .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Outer Cloister",              .act=ACT_1, .wp=WP_OUTER_CLOISTER},
    {.name="Barracks",                    .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Jail Level 1",                .act=ACT_1, .wp=WP_JAIL_LEVEL_1},
    {.name="Jail Level 2",                .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Jail Level 3",                .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Inner Cloister",              .act=ACT_1, .wp=WP_INNER_CLOISTER},
    {.name="Cathedral",                   .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Catacombs Level 1",           .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Catacombs Level 2",           .act=ACT_1, .wp=WP_CATACOMBS_LEVEL_2},
    {.name="Catacombs Level 3",           .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Catacombs Level 4",           .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Tristram",                    .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Moo Moo Farm",                .act=ACT_1, .wp=NO_WAYPOINT},
    {.name="Lut Gholein",                 .act=ACT_2, .wp=WP_LUT_GHOLEIN},
    {.name="Rocky Waste",                 .act=ACT_2, .wp=NO_WAYPOINT},
    {.name="Dry Hills",                   .act=ACT_2, .wp=WP_DRY_HILLS},
    {.name="Far Oasis",                   .act=ACT_2, .wp=WP_FAR_OASIS},
    {.name="Lost City",                   .act=ACT_2, .wp=WP_LOST_CITY},
    {.name="Valley of Snakes",            .act=ACT_2, .wp=NO_WAYPOINT},
    {.name="Canyon of the Magi",          .act=ACT_2, .wp=WP_CANYON_OF_THE_MAGI},
    {.name="Sewers Level 1",              .act=ACT_2, .wp=NO_WAYPOINT},
    {.name="Sewers Level 2",              .act=ACT_2, .wp=WP_SEWERS_LEVEL_2},
    {.name="Sewers Level 3",              .act=ACT_2, .wp=NO_WAYPOINT},
    {.name="Harem Level 1",               .act=ACT_2, .wp=NO_WAYPOINT},
    {.name="Harem Level 2",               .act=ACT_2, .wp=NO_WAYPOINT},
    {.name="Palace Cellar Level 1",       .act=ACT_2, .wp=WP_PALACE_CELLAR_LEVEL_1},
    {.name="Palace Cellar Level 2",       .act=ACT_2, .wp=NO_WAYPOINT},
    {.name="Palace Cellar Level 3",       .act=ACT_2, .wp=NO_WAYPOINT},
    {.name="Stony Tomb Level 1",          .act=ACT_2, .wp=NO_WAYPOINT},
    {.name="Halls of the Dead Level 1",   .act=ACT_2, .wp=NO_WAYPOINT},
    {.name="Halls of the Dead Level 2",   .act=ACT_2, .wp=WP_HALLS_OF_THE_DEAD_LEVEL_2},
    {.name="Claw Viper Temple Level 1",   .act=ACT_2, .wp=NO_WAYPOINT},
    {.name="Stony Tomb Level 2",          .act=ACT_2, .wp=NO_WAYPOINT},
    {.name="Halls of the Dead Level 3",   .act=ACT_2, .wp=NO_WAYPOINT},
    {.name="Claw Viper Temple Level 2",   .act=ACT_2, .wp=NO_WAYPOINT},
    {.name="Maggot Lair Level 1",         .act=ACT_2, .wp=NO_WAYPOINT},
    {.name="Maggot Lair Level 2",         .act=ACT_2, .wp=NO_WAYPOINT},
    {.name="Maggot Lair Level 3",         .act=ACT_2, .wp=NO_WAYPOINT},
    {.name="Ancient Tunnels",             .act=ACT_2, .wp=NO_WAYPOINT},
    {.name="Tal Rasha's Tomb",            .act=ACT_2, .wp=NO_WAYPOINT},
    {.name="Tal Rasha's Tomb",            .act=ACT_2, .wp=NO_WAYPOINT},
    {.name="Tal Rasha's Tomb",            .act=ACT_2, .wp=NO_WAYPOINT},
    {.name="Tal Rasha's Tomb",            .act=ACT_2, .wp=NO_WAYPOINT},
    {.name="Tal Rasha's Tomb",            .act=ACT_2, .wp=NO_WAYPOINT},
    {.name="Tal Rasha's Tomb",            .act=ACT_2, .wp=NO_WAYPOINT},
    {.name="Tal Rasha's Tomb",            .act=ACT_2, .wp=NO_WAYPOINT},
    {.name="Duriel's Lair",               .act=ACT_2, .wp=NO_WAYPOINT},
    {.name="Arcane Sanctuary",            .act=ACT_2, .wp=WP_ARCANE_SANCTUARY},
    {.name="Kurast Docktown",             .act=ACT_3, .wp=WP_KURAST_DOCKTOWN},
    {.name="Spider Forest",               .act=ACT_3, .wp=WP_SPIDER_FOREST},
    {.name="Great Marsh",                 .act=ACT_3, .wp=WP_GREAT_MARSH},
    {.name="Flayer Jungle",               .act=ACT_3, .wp=WP_FLAYER_JUNGLE},
    {.name="Lower Kurast",                .act=ACT_3, .wp=WP_LOWER_KURAST},
    {.name="Kurast Bazaar",               .act=ACT_3, .wp=WP_KURAST_BAZAAR},
    {.name="Upper Kurast",                .act=ACT_3, .wp=WP_UPPER_KURAST},
    {.name="Kurast Causeway",             .act=ACT_3, .wp=NO_WAYPOINT},
    {.name="Travincal",                   .act=ACT_3, .wp=WP_TRAVINCAL},
    {.name="Arachnid Lair",               .act=ACT_3, .wp=NO_WAYPOINT},
    {.name="Spider Cavern",               .act=ACT_3, .wp=NO_WAYPOINT},
    {.name="Swampy Pit Level 1",          .act=ACT_3, .wp=NO_WAYPOINT},
    {.name="Swampy Pit Level 2",          .act=ACT_3, .wp=NO_WAYPOINT},
    {.name="Flayer Dungeon Level 1",      .act=ACT_3, .wp=NO_WAYPOINT},
    {.name="Flayer Dungeon Level 2",      .act=ACT_3, .wp=NO_WAYPOINT},
    {.name="Swampy Pit Level 3",          .act=ACT_3, .wp=NO_WAYPOINT},
    {.name="Flayer Dungeon Level 3",      .act=ACT_3, .wp=NO_WAYPOINT},
    {.name="Sewers Level 1",              .act=ACT_3, .wp=NO_WAYPOINT},
    {.name="Sewers Level 2",              .act=ACT_3, .wp=NO_WAYPOINT},
    {.name="Ruined Temple",               .act=ACT_3, .wp=NO_WAYPOINT},
    {.name="Disused Fane",                .act=ACT_3, .wp=NO_WAYPOINT},
    {.name="Forgotten Reliquary",         .act=ACT_3, .wp=NO_WAYPOINT},
    {.name="Forgotten Temple",            .act=ACT_3, .wp=NO_WAYPOINT},
    {.name="Ruined Fane",                 .act=ACT_3, .wp=NO_WAYPOINT},
    {.name="Disused Reliquary",           .act=ACT_3, .wp=NO_WAYPOINT},
    {.name="Durance of Hate Level 1",     .act=ACT_3, .wp=NO_WAYPOINT},
    {.name="Durance of Hate Level 2",     .act=ACT_3, .wp=WP_DURANCE_OF_HATE_LEVEL_2},
    {.name="Durance of Hate Level 3",     .act=ACT_3, .wp=NO_WAYPOINT},
    {.name="The Pandemonium Fortress",    .act=ACT_4, .wp=WP_THE_PANDEMONIUM_FORTRESS},
    {.name="Outer Steppes",               .act=ACT_4, .wp=NO_WAYPOINT},
    {.name="Plains of Despair",           .act=ACT_4, .wp=NO_WAYPOINT},
    {.name="City of the Damned",          .act=ACT_4, .wp=WP_CITY_OF_THE_DAMNED},
    {.name="River of Flame",              .act=ACT_4, .wp=WP_RIVER_OF_FLAME},
    {.name="The Chaos Sanctuary",         .act=ACT_4, .wp=NO_WAYPOINT},
    {.name="Harrogath",                   .act=ACT_5, .wp=WP_HARROGATH},
    {.name="Bloody Foothills",            .act=ACT_5, .wp=NO_WAYPOINT},
    {.name="Frigid Highlands",            .act=ACT_5, .wp=WP_FRIGID_HIGHLANDS},
    {.name="Arreat Plateau",              .act=ACT_5, .wp=WP_ARREAT_PLATEAU},
    {.name="Crystalline Passage",         .act=ACT_5, .wp=WP_CRYSTALLINE_PASSAGE},
    {.name="Frozen River",                .act=ACT_5, .wp=NO_WAYPOINT},
    {.name="Glacial Trail",               .act=ACT_5, .wp=WP_GLACIAL_TRAIL},
    {.name="Drifter Cavern",              .act=ACT_5, .wp=NO_WAYPOINT},
    {.name="Frozen Tundra",               .act=ACT_5, .wp=WP_FROZEN_TUNDRA},
    {.name="The Ancients' Way",           .act=ACT_5, .wp=WP_THE_ANCIENTS_WAY},
    {.name="Icy Cellar",                  .act=ACT_5, .wp=NO_WAYPOINT},
    {.name="Arreat Summit",               .act=ACT_5, .wp=NO_WAYPOINT},
    {.name="Nihlathak's Temple",          .act=ACT_5, .wp=NO_WAYPOINT},
    {.name="Halls of Anguish",            .act=ACT_5, .wp=NO_WAYPOINT},
    {.name="Halls of Pain",               .act=ACT_5, .wp=WP_HALLS_OF_PAIN},
    {.name="Halls of Vaught",             .act=ACT_5, .wp=NO_WAYPOINT},
    {.name="Abaddon",                     .act=ACT_5, .wp=NO_WAYPOINT},
    {.name="Pit of Acheron",              .act=ACT_5, .wp=NO_WAYPOINT},
    {.name="Infernal Pit",                .act=ACT_5, .wp=NO_WAYPOINT},
    {.name="The Worldstone Keep Level 1", .act=ACT_5, .wp=NO_WAYPOINT},
    {.name="The Worldstone Keep Level 2", .act=ACT_5, .wp=WP_THE_WORLDSTONE_KEEP_LEVEL_2},
    {.name="The Worldstone Keep Level 3", .act=ACT_5, .wp=NO_WAYPOINT},
    {.name="Throne of Destruction",       .act=ACT_5, .wp=NO_WAYPOINT},
    {.name="The Worldstone Chamber",      .act=ACT_5, .wp=NO_WAYPOINT},
    {.name="Matron's Den",                .act=ACT_5, .wp=NO_WAYPOINT},
    {.name="Forgotten Sands",             .act=ACT_5, .wp=NO_WAYPOINT},
    {.name="Furnace of Pain",             .act=ACT_5, .wp=NO_WAYPOINT},
    {.name="Tristram",                    .act=ACT_5, .wp=NO_WAYPOINT}
};
