#include "sdk/level.h"

const ActInfo ACT_INFO[MAX_ACT] = {
    {.id=0, .name="Act I", .wp={
        ROGUE_ENCAMPMENT,
        COLD_PLAINS,
        STONY_FIELD,
        DARK_WOOD,
        BLACK_MARSH,
        OUTER_CLOISTER,
        JAIL_LEVEL_1,
        INNER_CLOISTER,
        CATACOMBS_LEVEL_2
    }},
    {.id=1, .name="Act II", .wp={
        LUT_GHOLEIN,
        SEWERS_LEVEL_2,
        DRY_HILLS,
        HALLS_OF_THE_DEAD_LEVEL_2,
        FAR_OASIS,
        LOST_CITY,
        PALACE_CELLAR_LEVEL_1,
        ARCANE_SANCTUARY,
        CANYON_OF_THE_MAGI
    }},
    {.id=2, .name="Act III", .wp={
        KURAST_DOCKTOWN,
        SPIDER_FOREST,
        GREAT_MARSH,
        FLAYER_JUNGLE,
        LOWER_KURAST,
        KURAST_BAZAAR,
        UPPER_KURAST,
        TRAVINCAL,
        DURANCE_OF_HATE_LEVEL_2
    }},
    {.id=3, .name="Act IV", .wp={
        THE_PANDEMONIUM_FORTRESS,
        CITY_OF_THE_DAMNED,
        RIVER_OF_FLAME
    }},
    {.id=4, .name="Act V", .wp={
        HARROGATH,
        FRIGID_HIGHLANDS,
        ARREAT_PLATEAU,
        CRYSTALLINE_PASSAGE,
        GLACIAL_TRAIL,
        HALLS_OF_PAIN,
        FROZEN_TUNDRA,
        THE_ANCIENTS_WAY,
        THE_WORLDSTONE_KEEP_LEVEL_2
    }}
};


const LevelInfo LEVEL_INFO[MAX_LEVEL] = {
    {.id=0, .name="Null",                        .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=1, .name="Rogue Encampment",            .act=ACT_1, .wp=WP_ROGUE_ENCAMPMENT},
    {.id=2, .name="Blood Moor",                  .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=3, .name="Cold Plains",                 .act=ACT_1, .wp=WP_COLD_PLAINS},
    {.id=4, .name="Stony Field",                 .act=ACT_1, .wp=WP_STONY_FIELD},
    {.id=5, .name="Dark Wood",                   .act=ACT_1, .wp=WP_DARK_WOOD},
    {.id=6, .name="Black Marsh",                 .act=ACT_1, .wp=WP_BLACK_MARSH},
    {.id=7, .name="Tamoe Highland",              .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=8, .name="Den of Evil",                 .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=9, .name="Cave Level 1",                .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=10, .name="Underground Passage Level 1", .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=11, .name="Hole Level 1",                .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=12, .name="Pit Level 1",                 .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=13, .name="Cave Level 2",                .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=14, .name="Underground Passage Level 2", .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=15, .name="Hole Level 2",                .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=16, .name="Pit Level 2",                 .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=17, .name="Burial Grounds",              .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=18, .name="Crypt",                       .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=19, .name="Mausoleum",                   .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=20, .name="Forgotten Tower",             .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=21, .name="Tower Cellar Level 1",        .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=22, .name="Tower Cellar Level 2",        .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=23, .name="Tower Cellar Level 3",        .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=24, .name="Tower Cellar Level 4",        .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=25, .name="Tower Cellar Level 5",        .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=26, .name="Monastery Gate",              .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=27, .name="Outer Cloister",              .act=ACT_1, .wp=WP_OUTER_CLOISTER},
    {.id=28, .name="Barracks",                    .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=29, .name="Jail Level 1",                .act=ACT_1, .wp=WP_JAIL_LEVEL_1},
    {.id=30, .name="Jail Level 2",                .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=31, .name="Jail Level 3",                .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=32, .name="Inner Cloister",              .act=ACT_1, .wp=WP_INNER_CLOISTER},
    {.id=33, .name="Cathedral",                   .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=34, .name="Catacombs Level 1",           .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=35, .name="Catacombs Level 2",           .act=ACT_1, .wp=WP_CATACOMBS_LEVEL_2},
    {.id=36, .name="Catacombs Level 3",           .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=37, .name="Catacombs Level 4",           .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=38, .name="Tristram",                    .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=39, .name="Moo Moo Farm",                .act=ACT_1, .wp=NO_WAYPOINT},
    {.id=40, .name="Lut Gholein",                 .act=ACT_2, .wp=WP_LUT_GHOLEIN},
    {.id=41, .name="Rocky Waste",                 .act=ACT_2, .wp=NO_WAYPOINT},
    {.id=42, .name="Dry Hills",                   .act=ACT_2, .wp=WP_DRY_HILLS},
    {.id=43, .name="Far Oasis",                   .act=ACT_2, .wp=WP_FAR_OASIS},
    {.id=44, .name="Lost City",                   .act=ACT_2, .wp=WP_LOST_CITY},
    {.id=45, .name="Valley of Snakes",            .act=ACT_2, .wp=NO_WAYPOINT},
    {.id=46, .name="Canyon of the Magi",          .act=ACT_2, .wp=WP_CANYON_OF_THE_MAGI},
    {.id=47, .name="Sewers Level 1",              .act=ACT_2, .wp=NO_WAYPOINT},
    {.id=48, .name="Sewers Level 2",              .act=ACT_2, .wp=WP_SEWERS_LEVEL_2},
    {.id=49, .name="Sewers Level 3",              .act=ACT_2, .wp=NO_WAYPOINT},
    {.id=50, .name="Harem Level 1",               .act=ACT_2, .wp=NO_WAYPOINT},
    {.id=51, .name="Harem Level 2",               .act=ACT_2, .wp=NO_WAYPOINT},
    {.id=52, .name="Palace Cellar Level 1",       .act=ACT_2, .wp=WP_PALACE_CELLAR_LEVEL_1},
    {.id=53, .name="Palace Cellar Level 2",       .act=ACT_2, .wp=NO_WAYPOINT},
    {.id=54, .name="Palace Cellar Level 3",       .act=ACT_2, .wp=NO_WAYPOINT},
    {.id=55, .name="Stony Tomb Level 1",          .act=ACT_2, .wp=NO_WAYPOINT},
    {.id=56, .name="Halls of the Dead Level 1",   .act=ACT_2, .wp=NO_WAYPOINT},
    {.id=57, .name="Halls of the Dead Level 2",   .act=ACT_2, .wp=WP_HALLS_OF_THE_DEAD_LEVEL_2},
    {.id=58, .name="Claw Viper Temple Level 1",   .act=ACT_2, .wp=NO_WAYPOINT},
    {.id=59, .name="Stony Tomb Level 2",          .act=ACT_2, .wp=NO_WAYPOINT},
    {.id=60, .name="Halls of the Dead Level 3",   .act=ACT_2, .wp=NO_WAYPOINT},
    {.id=61, .name="Claw Viper Temple Level 2",   .act=ACT_2, .wp=NO_WAYPOINT},
    {.id=62, .name="Maggot Lair Level 1",         .act=ACT_2, .wp=NO_WAYPOINT},
    {.id=63, .name="Maggot Lair Level 2",         .act=ACT_2, .wp=NO_WAYPOINT},
    {.id=64, .name="Maggot Lair Level 3",         .act=ACT_2, .wp=NO_WAYPOINT},
    {.id=65, .name="Ancient Tunnels",             .act=ACT_2, .wp=NO_WAYPOINT},
    {.id=66, .name="Tal Rasha's Tomb",            .act=ACT_2, .wp=NO_WAYPOINT},
    {.id=67, .name="Tal Rasha's Tomb",            .act=ACT_2, .wp=NO_WAYPOINT},
    {.id=68, .name="Tal Rasha's Tomb",            .act=ACT_2, .wp=NO_WAYPOINT},
    {.id=69, .name="Tal Rasha's Tomb",            .act=ACT_2, .wp=NO_WAYPOINT},
    {.id=70, .name="Tal Rasha's Tomb",            .act=ACT_2, .wp=NO_WAYPOINT},
    {.id=71, .name="Tal Rasha's Tomb",            .act=ACT_2, .wp=NO_WAYPOINT},
    {.id=72, .name="Tal Rasha's Tomb",            .act=ACT_2, .wp=NO_WAYPOINT},
    {.id=73, .name="Duriel's Lair",               .act=ACT_2, .wp=NO_WAYPOINT},
    {.id=74, .name="Arcane Sanctuary",            .act=ACT_2, .wp=WP_ARCANE_SANCTUARY},
    {.id=75, .name="Kurast Docktown",             .act=ACT_3, .wp=WP_KURAST_DOCKTOWN},
    {.id=76, .name="Spider Forest",               .act=ACT_3, .wp=WP_SPIDER_FOREST},
    {.id=77, .name="Great Marsh",                 .act=ACT_3, .wp=WP_GREAT_MARSH},
    {.id=78, .name="Flayer Jungle",               .act=ACT_3, .wp=WP_FLAYER_JUNGLE},
    {.id=79, .name="Lower Kurast",                .act=ACT_3, .wp=WP_LOWER_KURAST},
    {.id=80, .name="Kurast Bazaar",               .act=ACT_3, .wp=WP_KURAST_BAZAAR},
    {.id=81, .name="Upper Kurast",                .act=ACT_3, .wp=WP_UPPER_KURAST},
    {.id=82, .name="Kurast Causeway",             .act=ACT_3, .wp=NO_WAYPOINT},
    {.id=83, .name="Travincal",                   .act=ACT_3, .wp=WP_TRAVINCAL},
    {.id=84, .name="Arachnid Lair",               .act=ACT_3, .wp=NO_WAYPOINT},
    {.id=85, .name="Spider Cavern",               .act=ACT_3, .wp=NO_WAYPOINT},
    {.id=86, .name="Swampy Pit Level 1",          .act=ACT_3, .wp=NO_WAYPOINT},
    {.id=87, .name="Swampy Pit Level 2",          .act=ACT_3, .wp=NO_WAYPOINT},
    {.id=88, .name="Flayer Dungeon Level 1",      .act=ACT_3, .wp=NO_WAYPOINT},
    {.id=89, .name="Flayer Dungeon Level 2",      .act=ACT_3, .wp=NO_WAYPOINT},
    {.id=90, .name="Swampy Pit Level 3",          .act=ACT_3, .wp=NO_WAYPOINT},
    {.id=91, .name="Flayer Dungeon Level 3",      .act=ACT_3, .wp=NO_WAYPOINT},
    {.id=92, .name="Sewers Level 1",              .act=ACT_3, .wp=NO_WAYPOINT},
    {.id=93, .name="Sewers Level 2",              .act=ACT_3, .wp=NO_WAYPOINT},
    {.id=94, .name="Ruined Temple",               .act=ACT_3, .wp=NO_WAYPOINT},
    {.id=95, .name="Disused Fane",                .act=ACT_3, .wp=NO_WAYPOINT},
    {.id=96, .name="Forgotten Reliquary",         .act=ACT_3, .wp=NO_WAYPOINT},
    {.id=97, .name="Forgotten Temple",            .act=ACT_3, .wp=NO_WAYPOINT},
    {.id=98, .name="Ruined Fane",                 .act=ACT_3, .wp=NO_WAYPOINT},
    {.id=99, .name="Disused Reliquary",           .act=ACT_3, .wp=NO_WAYPOINT},
    {.id=100, .name="Durance of Hate Level 1",     .act=ACT_3, .wp=NO_WAYPOINT},
    {.id=101, .name="Durance of Hate Level 2",     .act=ACT_3, .wp=WP_DURANCE_OF_HATE_LEVEL_2},
    {.id=102, .name="Durance of Hate Level 3",     .act=ACT_3, .wp=NO_WAYPOINT},
    {.id=103, .name="The Pandemonium Fortress",    .act=ACT_4, .wp=WP_THE_PANDEMONIUM_FORTRESS},
    {.id=104, .name="Outer Steppes",               .act=ACT_4, .wp=NO_WAYPOINT},
    {.id=105, .name="Plains of Despair",           .act=ACT_4, .wp=NO_WAYPOINT},
    {.id=106, .name="City of the Damned",          .act=ACT_4, .wp=WP_CITY_OF_THE_DAMNED},
    {.id=107, .name="River of Flame",              .act=ACT_4, .wp=WP_RIVER_OF_FLAME},
    {.id=108, .name="The Chaos Sanctuary",         .act=ACT_4, .wp=NO_WAYPOINT},
    {.id=109, .name="Harrogath",                   .act=ACT_5, .wp=WP_HARROGATH},
    {.id=110, .name="Bloody Foothills",            .act=ACT_5, .wp=NO_WAYPOINT},
    {.id=111, .name="Frigid Highlands",            .act=ACT_5, .wp=WP_FRIGID_HIGHLANDS},
    {.id=112, .name="Arreat Plateau",              .act=ACT_5, .wp=WP_ARREAT_PLATEAU},
    {.id=113, .name="Crystalline Passage",         .act=ACT_5, .wp=WP_CRYSTALLINE_PASSAGE},
    {.id=114, .name="Frozen River",                .act=ACT_5, .wp=NO_WAYPOINT},
    {.id=115, .name="Glacial Trail",               .act=ACT_5, .wp=WP_GLACIAL_TRAIL},
    {.id=116, .name="Drifter Cavern",              .act=ACT_5, .wp=NO_WAYPOINT},
    {.id=117, .name="Frozen Tundra",               .act=ACT_5, .wp=WP_FROZEN_TUNDRA},
    {.id=118, .name="The Ancients' Way",           .act=ACT_5, .wp=WP_THE_ANCIENTS_WAY},
    {.id=119, .name="Icy Cellar",                  .act=ACT_5, .wp=NO_WAYPOINT},
    {.id=120, .name="Arreat Summit",               .act=ACT_5, .wp=NO_WAYPOINT},
    {.id=121, .name="Nihlathak's Temple",          .act=ACT_5, .wp=NO_WAYPOINT},
    {.id=122, .name="Halls of Anguish",            .act=ACT_5, .wp=NO_WAYPOINT},
    {.id=123, .name="Halls of Pain",               .act=ACT_5, .wp=WP_HALLS_OF_PAIN},
    {.id=124, .name="Halls of Vaught",             .act=ACT_5, .wp=NO_WAYPOINT},
    {.id=125, .name="Abaddon",                     .act=ACT_5, .wp=NO_WAYPOINT},
    {.id=126, .name="Pit of Acheron",              .act=ACT_5, .wp=NO_WAYPOINT},
    {.id=127, .name="Infernal Pit",                .act=ACT_5, .wp=NO_WAYPOINT},
    {.id=128, .name="The Worldstone Keep Level 1", .act=ACT_5, .wp=NO_WAYPOINT},
    {.id=129, .name="The Worldstone Keep Level 2", .act=ACT_5, .wp=WP_THE_WORLDSTONE_KEEP_LEVEL_2},
    {.id=130, .name="The Worldstone Keep Level 3", .act=ACT_5, .wp=NO_WAYPOINT},
    {.id=131, .name="Throne of Destruction",       .act=ACT_5, .wp=NO_WAYPOINT},
    {.id=132, .name="The Worldstone Chamber",      .act=ACT_5, .wp=NO_WAYPOINT},
    {.id=133, .name="Matron's Den",                .act=ACT_5, .wp=NO_WAYPOINT},
    {.id=134, .name="Forgotten Sands",             .act=ACT_5, .wp=NO_WAYPOINT},
    {.id=135, .name="Furnace of Pain",             .act=ACT_5, .wp=NO_WAYPOINT},
    {.id=136, .name="Tristram",                    .act=ACT_5, .wp=NO_WAYPOINT}
};
