#include "sdk/missile.h"

const MissileInfo MISSILE_INFO[MAX_MISSILE] = {
    {.id=0, .name="arrow"},
    {.id=1, .name="javelin"},
    {.id=2, .name="bighead1"},
    {.id=3, .name="bighead2"},
    {.id=4, .name="bighead3"},
    {.id=5, .name="bighead4"},
    {.id=6, .name="bighead5"},
    {.id=7, .name="spike1"},
    {.id=8, .name="spike2"},
    {.id=9, .name="spike3"},
    {.id=10, .name="spike4"},
    {.id=11, .name="spike5"},
    {.id=12, .name="firearrow"},
    {.id=13, .name="cr_arrow1"},
    {.id=14, .name="cr_arrow2"},
    {.id=15, .name="cr_arrow3"},
    {.id=16, .name="cr_arrow4"},
    {.id=17, .name="cr_arrow5"},
    {.id=18, .name="blood1"},
    {.id=19, .name="blood2"},
    {.id=20, .name="bigblood1"},
    {.id=21, .name="bigblood2"},
    {.id=22, .name="shafire1"},
    {.id=23, .name="shafire2"},
    {.id=24, .name="shafire3"},
    {.id=25, .name="shafire4"},
    {.id=26, .name="shafire5"},
    {.id=27, .name="magicarrow"},
    {.id=28, .name="icearrow"},
    {.id=29, .name="fireexplode"},
    {.id=30, .name="iceexplode"},
    {.id=31, .name="bolt"},
    {.id=32, .name="andarielspray"},
    {.id=33, .name="bigheadexp"},
    {.id=34, .name="shamanexp"},
    {.id=35, .name="throwaxe"},
    {.id=36, .name="throwknife"},
    {.id=37, .name="glaive"},
    {.id=38, .name="poisonjav"},
    {.id=39, .name="poisonjavcloud"},
    {.id=40, .name="coldarrow"},
    {.id=41, .name="explodingarrow"},
    {.id=42, .name="explodingarrowexp"},
    {.id=43, .name="plaguejavelin"},
    {.id=44, .name="oilpotion"},
    {.id=45, .name="explosivepotion"},
    {.id=46, .name="fulminatingpotion"},
    {.id=47, .name="rancidgasepotion"},
    {.id=48, .name="chokinggaspoition"},
    {.id=49, .name="stranglinggaspotion"},
    {.id=50, .name="notused50"},
    {.id=51, .name="explosivepotionexp"},
    {.id=52, .name="explosivepotiondebris1"},
    {.id=53, .name="explosivepotiondebris2"},
    {.id=54, .name="explosivepotiondebris3"},
    {.id=55, .name="holybolt"},
    {.id=56, .name="chargedbolt"},
    {.id=57, .name="sanctuarybolt"},
    {.id=58, .name="firebolt"},
    {.id=59, .name="icebolt"},
    {.id=60, .name="infernoflame1"},
    {.id=61, .name="infernoflame2"},
    {.id=62, .name="fireball"},
    {.id=63, .name="mummy1"},
    {.id=64, .name="mummy2"},
    {.id=65, .name="mummy3"},
    {.id=66, .name="mummy4"},
    {.id=67, .name="blaze"},
    {.id=68, .name="firewallmaker"},
    {.id=69, .name="firewall"},
    {.id=70, .name="goospit1"},
    {.id=71, .name="goospit2"},
    {.id=72, .name="goospit3"},
    {.id=73, .name="goospit4"},
    {.id=74, .name="goospit5"},
    {.id=75, .name="goosplat"},
    {.id=76, .name="sand pile"},
    {.id=77, .name="unholybolt1"},
    {.id=78, .name="unholybolt2"},
    {.id=79, .name="unholybolt3"},
    {.id=80, .name="unholybolt4"},
    {.id=81, .name="sanctuarycenter"},
    {.id=82, .name="fireexplosion"},
    {.id=83, .name="stuckarrow"},
    {.id=84, .name="footprint"},
    {.id=85, .name="immolationarrow"},
    {.id=86, .name="guidedarrow"},
    {.id=87, .name="freezingarrow"},
    {.id=88, .name="freezingarrowexp1"},
    {.id=89, .name="freezingarrowexp2"},
    {.id=90, .name="nova"},
    {.id=91, .name="iceblast"},
    {.id=92, .name="blessedhammer"},
    {.id=93, .name="chainlightning"},
    {.id=94, .name="fistofares"},
    {.id=95, .name="chillblood"},
    {.id=96, .name="glacialspike"},
    {.id=97, .name="teleport"},
    {.id=98, .name="lightningbolt"},
    {.id=99, .name="lightninghit"},
    {.id=100, .name="meteor"},
    {.id=101, .name="meteorcenter"},
    {.id=102, .name="meteortail"},
    {.id=103, .name="meteorexplode"},
    {.id=104, .name="firesmall"},
    {.id=105, .name="firemedium"},
    {.id=106, .name="monblizcenter"},
    {.id=107, .name="monbliz1"},
    {.id=108, .name="monbliz2"},
    {.id=109, .name="monbliz3"},
    {.id=110, .name="monbliz4"},
    {.id=111, .name="monblizexplode1"},
    {.id=112, .name="monblizexplode2"},
    {.id=113, .name="monblizexplode3"},
    {.id=114, .name="teeth"},
    {.id=115, .name="corpseexplosion"},
    {.id=116, .name="poisoncorpseexplosion"},
    {.id=117, .name="monstercorpseexplode"},
    {.id=118, .name="poisonnova"},
    {.id=119, .name="frostnova"},
    {.id=120, .name="rogue1"},
    {.id=121, .name="rogue2"},
    {.id=122, .name="rogue3"},
    {.id=123, .name="bat lightning bolt"},
    {.id=124, .name="bat lightning trail"},
    {.id=125, .name="skmage1"},
    {.id=126, .name="skmage2"},
    {.id=127, .name="skmage3"},
    {.id=128, .name="skmage4"},
    {.id=129, .name="vampirefireball"},
    {.id=130, .name="vampirefirewallmaker"},
    {.id=131, .name="vampirefirewall"},
    {.id=132, .name="vampiremeteor"},
    {.id=133, .name="vampiremeteorcenter"},
    {.id=134, .name="vampiremeteorexp"},
    {.id=135, .name="raven1"},
    {.id=136, .name="raven2"},
    {.id=137, .name="amphibiangoo1"},
    {.id=138, .name="amphibiangoo2"},
    {.id=139, .name="tentaclegoo"},
    {.id=140, .name="amphibianexplode"},
    {.id=141, .name="poisonpuff"},
    {.id=142, .name="curseeffectred"},
    {.id=143, .name="spidergoolay"},
    {.id=144, .name="fetishinferno1"},
    {.id=145, .name="fetishinferno2"},
    {.id=146, .name="spidergoo"},
    {.id=147, .name="cursecast"},
    {.id=148, .name="howl"},
    {.id=149, .name="shout"},
    {.id=150, .name="dust"},
    {.id=151, .name="redlightmissile"},
    {.id=152, .name="greenlightmissile"},
    {.id=153, .name="bluelightmissile"},
    {.id=154, .name="whitelightmissile"},
    {.id=155, .name="corpsepoisoncloud"},
    {.id=156, .name="chillbloodcloud"},
    {.id=157, .name="chillbloodpuff"},
    {.id=158, .name="blizzardcenter"},
    {.id=159, .name="blizzard1"},
    {.id=160, .name="blizzard2"},
    {.id=161, .name="blizzard3"},
    {.id=162, .name="blizzard4"},
    {.id=163, .name="blizzardexplode1"},
    {.id=164, .name="blizzardexplode2"},
    {.id=165, .name="blizzardexplode3"},
    {.id=166, .name="thunderstorm1"},
    {.id=167, .name="thunderstorm2"},
    {.id=168, .name="thunderstorm3"},
    {.id=169, .name="thunderstorm4"},
    {.id=170, .name="monsterlight"},
    {.id=171, .name="poisonball"},
    {.id=172, .name="diablight"},
    {.id=173, .name="redemption"},
    {.id=174, .name="redemptionfail"},
    {.id=175, .name="handofgod"},
    {.id=176, .name="diabfire"},
    {.id=177, .name="fingermagespider"},
    {.id=178, .name="electric throwaxe"},
    {.id=179, .name="diabwallmaker"},
    {.id=180, .name="diabwall"},
    {.id=181, .name="curseamplifydamage"},
    {.id=182, .name="cursedimvision"},
    {.id=183, .name="curseweaken"},
    {.id=184, .name="curseironmaiden"},
    {.id=185, .name="curseterror"},
    {.id=186, .name="curseattract"},
    {.id=187, .name="cursereversevampire"},
    {.id=188, .name="curseconfuse"},
    {.id=189, .name="cursedecrepify"},
    {.id=190, .name="curselowerresist"},
    {.id=191, .name="cursecenter"},
    {.id=192, .name="bonespear"},
    {.id=193, .name="bonespirit"},
    {.id=194, .name="coldunique"},
    {.id=195, .name="lightunique"},
    {.id=196, .name="skbowarrow1"},
    {.id=197, .name="skbowarrow2"},
    {.id=198, .name="skbowarrow3"},
    {.id=199, .name="skbowarrow4"},
    {.id=200, .name="skbowarrow5"},
    {.id=201, .name="nova1"},
    {.id=202, .name="nova2"},
    {.id=203, .name="andypoisonbolt"},
    {.id=204, .name="teethexplode"},
    {.id=205, .name="lightningjavelin"},
    {.id=206, .name="lightningfury"},
    {.id=207, .name="bonewallmaker"},
    {.id=208, .name="necromage1"},
    {.id=209, .name="necromage2"},
    {.id=210, .name="necromage3"},
    {.id=211, .name="necromage4"},
    {.id=212, .name="sparkle"},
    {.id=213, .name="multipleshotarrow"},
    {.id=214, .name="multipleshotbolt"},
    {.id=215, .name="chargedstrikebolt"},
    {.id=216, .name="bonespearexplode"},
    {.id=217, .name="poisonexplosioncloud"},
    {.id=218, .name="bonecast"},
    {.id=219, .name="battlecry"},
    {.id=220, .name="primepoisoncloud"},
    {.id=221, .name="plaguejavcloud"},
    {.id=222, .name="rancidgascloud"},
    {.id=223, .name="chokinggascloud"},
    {.id=224, .name="stranglinggascloud"},
    {.id=225, .name="buglightning"},
    {.id=226, .name="pantherjav1"},
    {.id=227, .name="pantherjav2"},
    {.id=228, .name="pantherjav3"},
    {.id=229, .name="pantherjav4"},
    {.id=230, .name="immolationfire"},
    {.id=231, .name="furylightning"},
    {.id=232, .name="lightningstrike"},
    {.id=233, .name="fistoftheheavensdelay"},
    {.id=234, .name="fistoftheheavensbolt"},
    {.id=235, .name="warcry"},
    {.id=236, .name="battlecommand"},
    {.id=237, .name="battleorders"},
    {.id=238, .name="pantherpotorange"},
    {.id=239, .name="pantherpotgreen"},
    {.id=240, .name="meteorfire"},
    {.id=241, .name="trap spike right"},
    {.id=242, .name="trap spike left"},
    {.id=243, .name="trap cursed skull right"},
    {.id=244, .name="trap cursed skull left"},
    {.id=245, .name="trap poison ball right"},
    {.id=246, .name="trap poison ball left"},
    {.id=247, .name="hydra"},
    {.id=248, .name="bonespeartrail"},
    {.id=249, .name="grimwardsmallstart"},
    {.id=250, .name="grimwardsmall"},
    {.id=251, .name="grimwardsmallstop"},
    {.id=252, .name="grimwardmediumstart"},
    {.id=253, .name="grimwardmedium"},
    {.id=254, .name="grimwardmediumstop"},
    {.id=255, .name="grimwardlargestart"},
    {.id=256, .name="grimwardlarge"},
    {.id=257, .name="grimwardlargestop"},
    {.id=258, .name="zakarumlight"},
    {.id=259, .name="grimwardscare"},
    {.id=260, .name="frozenorb"},
    {.id=261, .name="frozenorbbolt"},
    {.id=262, .name="frozenorbnova"},
    {.id=263, .name="frozenorbexplode"},
    {.id=264, .name="chillingarmorbolt"},
    {.id=265, .name="fireexplosion2"},
    {.id=266, .name="blowgun"},
    {.id=267, .name="chainlightning2"},
    {.id=268, .name="revivesmall"},
    {.id=269, .name="revivemedium"},
    {.id=270, .name="revivelarge"},
    {.id=271, .name="monglacialspike"},
    {.id=272, .name="icebreaksmall"},
    {.id=273, .name="icebreakmedium"},
    {.id=274, .name="icebreaklarge"},
    {.id=275, .name="icebreaksmoke"},
    {.id=276, .name="mephisto"},
    {.id=277, .name="firehead"},
    {.id=278, .name="whilrwind"},
    {.id=279, .name="arcanelightningbolt"},
    {.id=280, .name="frogfire"},
    {.id=281, .name="frogcold"},
    {.id=282, .name="frogpois"},
    {.id=283, .name="desertfireball"},
    {.id=284, .name="brdeathcontrol"},
    {.id=285, .name="brdeathlightningbolt"},
    {.id=286, .name="brdeathlightninghit"},
    {.id=287, .name="denofevillight"},
    {.id=288, .name="cairnstones"},
    {.id=289, .name="cairnstonessky"},
    {.id=290, .name="cairnstonesground"},
    {.id=291, .name="towermist"},
    {.id=292, .name="towermisttrail"},
    {.id=293, .name="brdeathsmokes1"},
    {.id=294, .name="brdeathsmokenu"},
    {.id=295, .name="brdeathsmokedt"},
    {.id=296, .name="brdeathspirits1"},
    {.id=297, .name="brdeathspiritnu"},
    {.id=298, .name="brdeathspiritdt"},
    {.id=299, .name="mephistodeathcontrol"},
    {.id=300, .name="mephistofirewallmaker"},
    {.id=301, .name="mephistofirewall"},
    {.id=302, .name="mephistoflyingrocksbig"},
    {.id=303, .name="mephistoexplosionbig"},
    {.id=304, .name="mephistoflyingrockssmall"},
    {.id=305, .name="mephistoexplosionsmall"},
    {.id=306, .name="mephistodonotdraw"},
    {.id=307, .name="andycontrol0"},
    {.id=308, .name="andyfirewallmaker"},
    {.id=309, .name="andyfirewall"},
    {.id=310, .name="andycolumnfirebase"},
    {.id=311, .name="andycolumnfire"},
    {.id=312, .name="andyfallingdebris1"},
    {.id=313, .name="andyfallingdebris2"},
    {.id=314, .name="andyfallingdebris3"},
    {.id=315, .name="andydebrisexplosion1"},
    {.id=316, .name="andydebrisexplosion2"},
    {.id=317, .name="andydebrisexplosion3"},
    {.id=318, .name="andydebrisexplosion4"},
    {.id=319, .name="andydebrisexplosion5"},
    {.id=320, .name="willowisplightningbolt"},
    {.id=321, .name="queenpoisoncloud"},
    {.id=322, .name="dirt pile"},
    {.id=323, .name="undeadmissile1"},
    {.id=324, .name="undeadmissile2"},
    {.id=325, .name="undeadmissile3"},
    {.id=326, .name="undeadmissile4"},
    {.id=327, .name="bonespiritexplode"},
    {.id=328, .name="dopplezonexplode"},
    {.id=329, .name="monbonespirit"},
    {.id=330, .name="towermistfade"},
    {.id=331, .name="countessfirewall"},
    {.id=332, .name="towerchestspawner"},
    {.id=333, .name="hellmeteorlaunch1"},
    {.id=334, .name="hellmeteorlaunch2"},
    {.id=335, .name="hellmeteorup"},
    {.id=336, .name="hellmeteordown"},
    {.id=337, .name="hellmeteorball"},
    {.id=338, .name="horadricstaff"},
    {.id=339, .name="horadriclightning"},
    {.id=340, .name="horadriclight"},
    {.id=341, .name="regurgitatorcorpse"},
    {.id=342, .name="regurgitatorcorpseexpl"},
    {.id=343, .name="highpriestlightning"},
    {.id=344, .name="icebreaksmallmelt"},
    {.id=345, .name="icebreaklargemelt"},
    {.id=346, .name="leapknockback"},
    {.id=347, .name="radamentdeath"},
    {.id=348, .name="radamenthandofgod"},
    {.id=349, .name="radamentholybolt"},
    {.id=350, .name="taintedsuncontrol"},
    {.id=351, .name="taintedsunflash"},
    {.id=352, .name="taintedsunball"},
    {.id=353, .name="queendeathcenter"},
    {.id=354, .name="queendeathglob"},
    {.id=355, .name="queendeathsplat1"},
    {.id=356, .name="queendeathsplat2"},
    {.id=357, .name="healingbolt"},
    {.id=358, .name="mephistoholedelay"},
    {.id=359, .name="mephistoholebirth"},
    {.id=360, .name="mephistoholeneutral"},
    {.id=361, .name="mephistoholedeath"},
    {.id=362, .name="mephistoholedead"},
    {.id=363, .name="durieldeathcontrol"},
    {.id=364, .name="durieldeathrock"},
    {.id=365, .name="durieldeathdebris"},
    {.id=366, .name="durieldeathsmoke"},
    {.id=367, .name="mephistoexplosion"},
    {.id=368, .name="orbmist"},
    {.id=369, .name="orbmisttrail"},
    {.id=370, .name="orbmistfade"},
    {.id=371, .name="pilum"},
    {.id=372, .name="diablo appears"},
    {.id=373, .name="hfcontrol"},
    {.id=374, .name="hffragment1"},
    {.id=375, .name="hffragment2"},
    {.id=376, .name="hffragment3"},
    {.id=377, .name="hfspirit1"},
    {.id=378, .name="hfreserved3"},
    {.id=379, .name="izual control"},
    {.id=380, .name="izual mist loop"},
    {.id=381, .name="izual mist fade"},
    {.id=382, .name="izual lightning"},
    {.id=383, .name="izual lightning trail"},
    {.id=384, .name="cairn stones bolt"},
    {.id=385, .name="bomb in air"},
    {.id=386, .name="bomb on ground"},
    {.id=387, .name="bomb explosion"},
    {.id=388, .name="shock field in air"},
    {.id=389, .name="shock field on ground"},
    {.id=390, .name="throwingstar"},
    {.id=391, .name="acidspray"},
    {.id=392, .name="blade creeper"},
    {.id=393, .name="distraction"},
    {.id=394, .name="distraction fog"},
    {.id=395, .name="distraction puff"},
    {.id=396, .name="distraction start"},
    {.id=397, .name="distraction end"},
    {.id=398, .name="impinfernoflame1"},
    {.id=399, .name="impinfernoflame2"},
    {.id=400, .name="baallightningbolt"},
    {.id=401, .name="baallightningtrail"},
    {.id=402, .name="baallightningbolt2"},
    {.id=403, .name="baallightningtrail2"},
    {.id=404, .name="impfireball"},
    {.id=405, .name="impfireballexplode"},
    {.id=406, .name="catapultchargedball on"},
    {.id=407, .name="catapultchargedball"},
    {.id=408, .name="catapultchargedballbolt"},
    {.id=409, .name="imp spawn monsters"},
    {.id=410, .name="catapult spike ball on"},
    {.id=411, .name="catapult spike ball"},
    {.id=412, .name="catapult spike in air"},
    {.id=413, .name="catapult spike on ground"},
    {.id=414, .name="catapult spike explosion"},
    {.id=415, .name="catapult cold ball on"},
    {.id=416, .name="catapult cold ball"},
    {.id=417, .name="catapult cold explosion"},
    {.id=418, .name="catapult plague ball on"},
    {.id=419, .name="catapult plague ball"},
    {.id=420, .name="catapult plague cloud"},
    {.id=421, .name="catapult meteor ball on"},
    {.id=422, .name="catapult meteor ball"},
    {.id=423, .name="catapult meteor fire"},
    {.id=424, .name="tower death"},
    {.id=425, .name="healing vortex"},
    {.id=426, .name="suicidecorpseexplode"},
    {.id=427, .name="suicidefireexplode"},
    {.id=428, .name="suicideiceexplode"},
    {.id=429, .name="explodingjavalin"},
    {.id=430, .name="explodingjavalinexp"},
    {.id=431, .name="lightingtrailingjavalin"},
    {.id=432, .name="lightjavalintrail"},
    {.id=433, .name="lightjavalinexplosion"},
    {.id=434, .name="icejavalin"},
    {.id=435, .name="icejavalinexplode"},
    {.id=436, .name="plaguejavelin2"},
    {.id=437, .name="plaguejavlinexplode"},
    {.id=438, .name="advlighttrailingjav"},
    {.id=439, .name="advlighttrailingjav2"},
    {.id=440, .name="advlightjavexplode"},
    {.id=441, .name="sucfireball"},
    {.id=442, .name="sucfireballexplode"},
    {.id=443, .name="sucfireballtrail"},
    {.id=444, .name="sucshockfieldmissile"},
    {.id=445, .name="sucshockfieldmissileexp"},
    {.id=446, .name="sucshockfield"},
    {.id=447, .name="hellfiremissile"},
    {.id=448, .name="hellfireexa"},
    {.id=449, .name="hellfireexb"},
    {.id=450, .name="imp charged bolt"},
    {.id=451, .name="imp teleport"},
    {.id=452, .name="moltenboulder"},
    {.id=453, .name="moltenboulderemerge"},
    {.id=454, .name="moltenboulderexplode"},
    {.id=455, .name="moltenboulderfirepath"},
    {.id=456, .name="moltenboulder-flyingrocks"},
    {.id=457, .name="firestorm"},
    {.id=458, .name="firestormmaker"},
    {.id=459, .name="arcticblast1"},
    {.id=460, .name="arcticblast2"},
    {.id=461, .name="erruption center"},
    {.id=462, .name="erruption crack 1"},
    {.id=463, .name="erruption crack 2"},
    {.id=464, .name="erruption smoke 1"},
    {.id=465, .name="erruption smoke 2"},
    {.id=466, .name="vine beast walk 1"},
    {.id=467, .name="vine beast walk 2"},
    {.id=468, .name="vine beast neutral"},
    {.id=469, .name="vine beast attack"},
    {.id=470, .name="vine beast death"},
    {.id=471, .name="vines"},
    {.id=472, .name="vines trail"},
    {.id=473, .name="vines wither"},
    {.id=474, .name="plague vines"},
    {.id=475, .name="plague vines trail"},
    {.id=476, .name="plague vines wither"},
    {.id=477, .name="twister"},
    {.id=478, .name="tornado"},
    {.id=479, .name="volcano"},
    {.id=480, .name="volcano overlay fire"},
    {.id=481, .name="volcano debris 2"},
    {.id=482, .name="volcano explosion"},
    {.id=483, .name="volcano small fire"},
    {.id=484, .name="dragonbreath missile"},
    {.id=485, .name="lureprojectile"},
    {.id=486, .name="lurecenter"},
    {.id=487, .name="lurecloud"},
    {.id=488, .name="impmiss1"},
    {.id=489, .name="impmiss2"},
    {.id=490, .name="impmiss3"},
    {.id=491, .name="impmiss4"},
    {.id=492, .name="impmiss5"},
    {.id=493, .name="frozenhorror arcticblast1"},
    {.id=494, .name="frozenhorror arcticblast2"},
    {.id=495, .name="sentrychargedbolt"},
    {.id=496, .name="sentryspikeinair"},
    {.id=497, .name="sentryspikeonground"},
    {.id=498, .name="recycler delay"},
    {.id=499, .name="recycler vine"},
    {.id=500, .name="recycler fade"},
    {.id=501, .name="recycler explosion"},
    {.id=502, .name="death mauler"},
    {.id=503, .name="death mauler trail"},
    {.id=504, .name="death mauler trail fade"},
    {.id=505, .name="bladefury1"},
    {.id=506, .name="bladefragment1"},
    {.id=507, .name="bladefury2"},
    {.id=508, .name="bladefragment2"},
    {.id=509, .name="bladefury3"},
    {.id=510, .name="bladefragment3"},
    {.id=511, .name="shockwave"},
    {.id=512, .name="lightningtalons"},
    {.id=513, .name="lightningtalonstrail"},
    {.id=514, .name="phoenixtrail"},
    {.id=515, .name="rabiesplague"},
    {.id=516, .name="rabiescontagion"},
    {.id=517, .name="wake of destruction maker"},
    {.id=518, .name="wake of destruction"},
    {.id=519, .name="deathsentryexplode"},
    {.id=520, .name="tigerfury"},
    {.id=521, .name="tigerfurytrail"},
    {.id=522, .name="tigerfurytrail2"},
    {.id=523, .name="inferno sentry 1"},
    {.id=524, .name="inferno sentry 2"},
    {.id=525, .name="ancient throwing axe"},
    {.id=526, .name="sentrylightningbolt"},
    {.id=527, .name="sentrylightninghit"},
    {.id=528, .name="anya center"},
    {.id=529, .name="anya icicle"},
    {.id=530, .name="anya iceimpact"},
    {.id=531, .name="anya icesteam"},
    {.id=532, .name="anya icemagic"},
    {.id=533, .name="dragontail missile"},
    {.id=534, .name="dragonflight"},
    {.id=535, .name="dragonflightmaker"},
    {.id=536, .name="progressive radius damage"},
    {.id=537, .name="vine beast walk 1 fade"},
    {.id=538, .name="vine beast walk 2 fade"},
    {.id=539, .name="vine beast neutral fade"},
    {.id=540, .name="vine recycler delay"},
    {.id=541, .name="ancient death center"},
    {.id=542, .name="ancient death cloud"},
    {.id=543, .name="lightning charge up nova"},
    {.id=544, .name="chainlightningcharge up"},
    {.id=545, .name="pain worm appear"},
    {.id=546, .name="baal taunt control"},
    {.id=547, .name="baal taunt lightning"},
    {.id=548, .name="baal taunt lightning trail"},
    {.id=549, .name="baal taunt poison"},
    {.id=550, .name="baal spawn monsters"},
    {.id=551, .name="mindblast hit"},
    {.id=552, .name="blade shield missile"},
    {.id=553, .name="blade shield attachment"},
    {.id=554, .name="baal inferno"},
    {.id=555, .name="baal nova"},
    {.id=556, .name="fistsoffireexplode"},
    {.id=557, .name="fistsoffirefirewall"},
    {.id=558, .name="clawsofthunderbolt"},
    {.id=559, .name="clawsofthundernova"},
    {.id=560, .name="bladesoficeexplode"},
    {.id=561, .name="bladesoficecubes"},
    {.id=562, .name="bladesoficecubesmelt"},
    {.id=563, .name="royalstrikemeteor"},
    {.id=564, .name="royalstrikemeteorcenter"},
    {.id=565, .name="royalstrikemeteortail"},
    {.id=566, .name="royalstrikemeteorexplode"},
    {.id=567, .name="royalstrikemeteorfire"},
    {.id=568, .name="royalstrikechainlightning"},
    {.id=569, .name="royalstrikechaosice"},
    {.id=570, .name="world stone chip 1"},
    {.id=571, .name="world stone chip 2"},
    {.id=572, .name="world stone chip 3"},
    {.id=573, .name="world stone chip 4"},
    {.id=574, .name="highpriestlightning2"},
    {.id=575, .name="infernoflame3"},
    {.id=576, .name="mindblast center"},
    {.id=577, .name="armageddoncontrol"},
    {.id=578, .name="armageddonrock"},
    {.id=579, .name="armageddontail"},
    {.id=580, .name="armageddonexplosion"},
    {.id=581, .name="hurricaneswoosh"},
    {.id=582, .name="hurricanecart"},
    {.id=583, .name="hurricanerock"},
    {.id=584, .name="hurricanesack"},
    {.id=585, .name="hurricanetree"},
    {.id=586, .name="hurricanevase"},
    {.id=587, .name="baalcorpseexplodedelay"},
    {.id=588, .name="baalcorpseexplodeexpl"},
    {.id=589, .name="baal cold maker"},
    {.id=590, .name="baal cold trail"},
    {.id=591, .name="baal spawn monsters exp"},
    {.id=592, .name="impmiss21"},
    {.id=593, .name="impmiss22"},
    {.id=594, .name="impmiss23"},
    {.id=595, .name="impmiss24"},
    {.id=596, .name="impmiss25"},
    {.id=597, .name="anyasteam1"},
    {.id=598, .name="anyasteam2"},
    {.id=599, .name="ancientsguide"},
    {.id=600, .name="ancientsmarker"},
    {.id=601, .name="ancientscontrol"},
    {.id=602, .name="overseercontrol"},
    {.id=603, .name="nihlithak1"},
    {.id=604, .name="nihlithak2"},
    {.id=605, .name="nihlithak3"},
    {.id=606, .name="nihlathakcontrol"},
    {.id=607, .name="nihlathakswoosh"},
    {.id=608, .name="nihlathakdebris1"},
    {.id=609, .name="nihlathakdebris2"},
    {.id=610, .name="nihlathakdebris3"},
    {.id=611, .name="nihlathakdebris4"},
    {.id=612, .name="nihlathakglow"},
    {.id=613, .name="baalteleport"},
    {.id=614, .name="baalclonedeath"},
    {.id=615, .name="anyasteamvent"},
    {.id=616, .name="anyasteam"},
    {.id=617, .name="nihlathakhole"},
    {.id=618, .name="nihlathakholelight"},
    {.id=619, .name="volcanofiretrail"},
    {.id=620, .name="nihlathakglow2"},
    {.id=621, .name="nihlathakbonechips"},
    {.id=622, .name="baalcorpseexplodefade"},
    {.id=623, .name="armageddonfire"},
    {.id=624, .name="icesparkle"},
    {.id=625, .name="baalfx control"},
    {.id=626, .name="baalfx spirit 1"},
    {.id=627, .name="baalfx spirit 2"},
    {.id=628, .name="baalfx spirit 3"},
    {.id=629, .name="baalfx spirit 4"},
    {.id=630, .name="baalfx spirit 5"},
    {.id=631, .name="baalfx baal head appear"},
    {.id=632, .name="baalfx baal head 1"},
    {.id=633, .name="baalfx baal head 2"},
    {.id=634, .name="baalfx baal head 3"},
    {.id=635, .name="baalfx tyreal debris 1"},
    {.id=636, .name="baalfx tyreal debris 2"},
    {.id=637, .name="baalfx tyreal debris 3"},
    {.id=638, .name="baalfx tyreal debris break"},
    {.id=639, .name="worldstone shake"},
    {.id=640, .name="blessedhammerex"},
    {.id=641, .name="sentrylightningbolt2"},
    {.id=642, .name="sentrylightninghit2"},
    {.id=643, .name="lightningtowernova"},
    {.id=644, .name="skbowarrow6"},
    {.id=645, .name="skbowarrow7"},
    {.id=646, .name="skbowarrow8"},
    {.id=647, .name="bighead6"},
    {.id=648, .name="viper_poisjav"},
    {.id=649, .name="viper_poisjavcloud"},
    {.id=650, .name="viper_fire"},
    {.id=651, .name="viper_firecloud"},
    {.id=652, .name="viper_bonespear"},
    {.id=653, .name="countessfirewallmaker"},
    {.id=654, .name="baal taunt lightning control"},
    {.id=655, .name="baal taunt poison control"},
    {.id=656, .name="explodingarrowexp2"},
    {.id=657, .name="freezingarrowexp3"},
    {.id=658, .name="pantherjav5"},
    {.id=659, .name="spike6"},
    {.id=660, .name="cr_arrow6"},
    {.id=661, .name="skmagepois"},
    {.id=662, .name="skmagecold"},
    {.id=663, .name="skmagefire"},
    {.id=664, .name="skmageltng"},
    {.id=665, .name="succubusmiss"},
    {.id=666, .name="willowisplightningbolt2"},
    {.id=667, .name="mummyex"},
    {.id=668, .name="goospitex"},
    {.id=669, .name="impmissex"},
    {.id=670, .name="diablogeddoncontrol"},
    {.id=671, .name="diablogeddonrock"},
    {.id=672, .name="diablogeddontail"},
    {.id=673, .name="diablogeddonexplosion"},
    {.id=674, .name="diablogeddonfire"},
    {.id=675, .name="megademoninferno"},
    {.id=676, .name="trapfirebolt"},
    {.id=677, .name="trappoisonjavcloud"},
    {.id=678, .name="trapnova"},
    {.id=679, .name="mephfrostnova"},
    {.id=680, .name="mephlight"},
    {.id=681, .name="vampiremeteorfire"},
    {.id=682, .name="strafearrow"},
    {.id=683, .name="strafebolt"},
    {.id=684, .name="recklessattacksmissile"},
    {.id=685, .name="leapattack"}
};
