#include "sdk/tile.h"

const UniqueTileInfo UNIQUE_TILE_INFO[MAX_UNIQUE_TILE] = {
    {.id=0,         .name="Act 1 Wilderness to Cave Cliff L",
     .noInteract=0, .notUniqueId=TILE_ACT_1_WILDERNESS_TO_CAVE_CLIFF_L},
    {.id=1,         .name="Act 1 Wilderness to Cave Cliff R",
     .noInteract=0, .notUniqueId=TILE_ACT_1_WILDERNESS_TO_CAVE_CLIFF_R},
    {.id=2,         .name="Act 1 Wilderness to Cave Floor L",
     .noInteract=0, .notUniqueId=TILE_ACT_1_WILDERNESS_TO_CAVE_FLOOR_L},
    {.id=3,         .name="Act 1 Wilderness to Cave Floor R",
     .noInteract=0, .notUniqueId=TILE_ACT_1_WILDERNESS_TO_CAVE_FLOOR_R},
    {.id=4,         .name="Act 1 Cave Up",
     .noInteract=0, .notUniqueId=TILE_ACT_1_CAVE_UP},
    {.id=5,         .name="Act 1 Cave Down",
     .noInteract=0, .notUniqueId=TILE_ACT_1_CAVE_DOWN},
    {.id=6,         .name="Act 1 Graveyard to Crypt 1",
     .noInteract=0, .notUniqueId=TILE_ACT_1_GRAVEYARD_TO_CRYPT_1},
    {.id=7,         .name="Act 1 Graveyard to Crypt 2",
     .noInteract=0, .notUniqueId=TILE_ACT_1_GRAVEYARD_TO_CRYPT_2},
    {.id=8,         .name="Act 1 Crypt Up",
     .noInteract=0, .notUniqueId=TILE_ACT_1_CRYPT_UP},
    {.id=9,         .name="Act 1 Crypt Down",
     .noInteract=0, .notUniqueId=TILE_ACT_1_CRYPT_DOWN},
    {.id=10,         .name="Act 1 Wilderness to Tower",
     .noInteract=0, .notUniqueId=TILE_ACT_1_WILDERNESS_TO_TOWER},
    {.id=11,         .name="Act 1 Tower to Wilderness",
     .noInteract=0, .notUniqueId=TILE_ACT_1_TOWER_TO_WILDERNESS},
    {.id=12,         .name="Act 1 Tower to Crypt",
     .noInteract=0, .notUniqueId=TILE_ACT_1_TOWER_TO_CRYPT},
    {.id=13,         .name="Act 1 Jail Up",
     .noInteract=0, .notUniqueId=TILE_ACT_1_JAIL_UP},
    {.id=14,         .name="Act 1 Jail Down",
     .noInteract=0, .notUniqueId=TILE_ACT_1_JAIL_DOWN},
    {.id=15,         .name="Act 1 Cathedral To Catacombs",
     .noInteract=0, .notUniqueId=TILE_ACT_1_CATHEDRAL_TO_CATACOMBS},
    {.id=16,         .name="Act 1 Catacombs to Cathedral",
     .noInteract=0, .notUniqueId=TILE_ACT_1_CATACOMBS_TO_CATHEDRAL},
    {.id=17,         .name="Act 1 Catacombs Up",
     .noInteract=0, .notUniqueId=TILE_ACT_1_CATACOMBS_UP},
    {.id=18,         .name="Act 1 Catacombs Down",
     .noInteract=0, .notUniqueId=TILE_ACT_1_CATACOMBS_DOWN},
    {.id=19,         .name="Act 2 Town to Sewer Trap",
     .noInteract=1, .notUniqueId=TILE_ACT_2_TOWN_TO_SEWER_TRAP},
    {.id=20,         .name="Act 2 Town to Sewer Dock",
     .noInteract=0, .notUniqueId=TILE_ACT_2_TOWN_TO_SEWER_DOCK},
    {.id=21,         .name="Act 2 Sewer Dock to Town",
     .noInteract=0, .notUniqueId=TILE_ACT_2_SEWER_DOCK_TO_TOWN},
    {.id=22,         .name="Act 2 Sewer Up",
     .noInteract=0, .notUniqueId=TILE_ACT_2_SEWER_UP},
    {.id=23,         .name="Act 2 Sewer Down",
     .noInteract=0, .notUniqueId=TILE_ACT_2_SEWER_DOWN},
    {.id=24,         .name="Act 2 Town to Harem",
     .noInteract=0, .notUniqueId=TILE_ACT_2_TOWN_TO_HAREM},
    {.id=25,         .name="Act 2 Harem to Town",
     .noInteract=0, .notUniqueId=TILE_ACT_2_HAREM_TO_TOWN},
    {.id=26,         .name="Act 2 Harem Up 1",
     .noInteract=0, .notUniqueId=TILE_ACT_2_HAREM_UP_1},
    {.id=27,         .name="Act 2 Harem Up 2",
     .noInteract=0, .notUniqueId=TILE_ACT_2_HAREM_UP_2},
    {.id=28,         .name="Act 2 Harem Down 1",
     .noInteract=0, .notUniqueId=TILE_ACT_2_HAREM_DOWN_1},
    {.id=29,         .name="Act 2 Harem Down 2",
     .noInteract=0, .notUniqueId=TILE_ACT_2_HAREM_DOWN_2},
    {.id=30,         .name="Act 2 Basement Up 1",
     .noInteract=0, .notUniqueId=TILE_ACT_2_BASEMENT_UP_1},
    {.id=31,         .name="Act 2 Basement Up 2",
     .noInteract=0, .notUniqueId=TILE_ACT_2_BASEMENT_UP_2},
    {.id=32,         .name="Act 2 Basement Down",
     .noInteract=0, .notUniqueId=TILE_ACT_2_BASEMENT_DOWN},
    {.id=33,         .name="Act 2 Desert to Tomb L 1",
     .noInteract=0, .notUniqueId=TILE_ACT_2_DESERT_TO_TOMB_L_1},
    {.id=34,         .name="Act 2 Desert to Tomb L 2",
     .noInteract=0, .notUniqueId=TILE_ACT_2_DESERT_TO_TOMB_L_2},
    {.id=35,         .name="Act 2 Desert to Tomb R 1",
     .noInteract=0, .notUniqueId=TILE_ACT_2_DESERT_TO_TOMB_R_1},
    {.id=36,         .name="Act 2 Desert to Tomb R 2",
     .noInteract=0, .notUniqueId=TILE_ACT_2_DESERT_TO_TOMB_R_2},
    {.id=37,         .name="Act 2 Desert to Tomb Viper",
     .noInteract=0, .notUniqueId=TILE_ACT_2_DESERT_TO_TOMB_VIPER},
    {.id=38,         .name="Act 2 Desert to Tomb Tal 1",
     .noInteract=0, .notUniqueId=TILE_ACT_2_DESERT_TO_TOMB_TAL_1},
    {.id=39,         .name="Act 2 Desert to Tomb Tal 2",
     .noInteract=0, .notUniqueId=TILE_ACT_2_DESERT_TO_TOMB_TAL_2},
    {.id=40,         .name="Act 2 Desert to Tomb Tal 3",
     .noInteract=0, .notUniqueId=TILE_ACT_2_DESERT_TO_TOMB_TAL_3},
    {.id=41,         .name="Act 2 Desert to Tomb Tal 4",
     .noInteract=0, .notUniqueId=TILE_ACT_2_DESERT_TO_TOMB_TAL_4},
    {.id=42,         .name="Act 2 Desert to Tomb Tal 5",
     .noInteract=0, .notUniqueId=TILE_ACT_2_DESERT_TO_TOMB_TAL_5},
    {.id=43,         .name="Act 2 Desert to Tomb Tal 6",
     .noInteract=0, .notUniqueId=TILE_ACT_2_DESERT_TO_TOMB_TAL_6},
    {.id=44,         .name="Act 2 Desert to Tomb Tal 7",
     .noInteract=0, .notUniqueId=TILE_ACT_2_DESERT_TO_TOMB_TAL_7},
    {.id=45,         .name="Act 2 Tomb Up",
     .noInteract=0, .notUniqueId=TILE_ACT_2_TOMB_UP},
    {.id=46,         .name="Act 2 Tomb Down",
     .noInteract=0, .notUniqueId=TILE_ACT_2_TOMB_DOWN},
    {.id=47,         .name="Act 2 Desert to Lair",
     .noInteract=0, .notUniqueId=TILE_ACT_2_DESERT_TO_LAIR},
    {.id=48,         .name="Act 2 Lair Up",
     .noInteract=0, .notUniqueId=TILE_ACT_2_LAIR_UP},
    {.id=49,         .name="Act 2 Lair Down",
     .noInteract=0, .notUniqueId=TILE_ACT_2_LAIR_DOWN},
    {.id=50,         .name="Act 2 Desert to Sewer Trap",
     .noInteract=1, .notUniqueId=TILE_ACT_2_DESERT_TO_SEWER_TRAP},
    {.id=51,         .name="Act 3 Jungle to Spider",
     .noInteract=0, .notUniqueId=TILE_ACT_3_JUNGLE_TO_SPIDER},
    {.id=52,         .name="Act 3 Spider to Jungle",
     .noInteract=0, .notUniqueId=TILE_ACT_3_SPIDER_TO_JUNGLE},
    {.id=53,         .name="Act 3 Jungle to Dungeon Fort",
     .noInteract=0, .notUniqueId=TILE_ACT_3_JUNGLE_TO_DUNGEON_FORT},
    {.id=54,         .name="Act 3 Jungle to Dungeon Hole",
     .noInteract=0, .notUniqueId=TILE_ACT_3_JUNGLE_TO_DUNGEON_HOLE},
    {.id=55,         .name="Act 3 Dungeon Up",
     .noInteract=0, .notUniqueId=TILE_ACT_3_DUNGEON_UP},
    {.id=56,         .name="Act 3 Dungeon Down",
     .noInteract=0, .notUniqueId=TILE_ACT_3_DUNGEON_DOWN},
    {.id=57,         .name="Act 3 Kurast to Sewer",
     .noInteract=0, .notUniqueId=TILE_ACT_3_KURAST_TO_SEWER},
    {.id=58,         .name="Act 3 Sewer Up L",
     .noInteract=0, .notUniqueId=TILE_ACT_3_SEWER_UP_L},
    {.id=59,         .name="Act 3 Sewer Up R",
     .noInteract=0, .notUniqueId=TILE_ACT_3_SEWER_UP_R},
    {.id=60,         .name="Act 3 Sewer Down",
     .noInteract=1, .notUniqueId=TILE_ACT_3_SEWER_DOWN},
    {.id=61,         .name="Act 3 Kurast to Temple",
     .noInteract=1, .notUniqueId=TILE_ACT_3_KURAST_TO_TEMPLE},
    {.id=62,         .name="Act 3 Temple Up L",
     .noInteract=0, .notUniqueId=TILE_ACT_3_TEMPLE_UP_L},
    {.id=63,         .name="Act 3 Temple Up R",
     .noInteract=0, .notUniqueId=TILE_ACT_3_TEMPLE_UP_R},
    {.id=64,         .name="Act 3 Travincal to Mephisto",
     .noInteract=1, .notUniqueId=TILE_ACT_3_TRAVINCAL_TO_MEPHISTO},
    {.id=65,         .name="Act 3 Mephisto Up L",
     .noInteract=0, .notUniqueId=TILE_ACT_3_MEPHISTO_UP_L},
    {.id=66,         .name="Act 3 Mephisto Up R",
     .noInteract=0, .notUniqueId=TILE_ACT_3_MEPHISTO_UP_R},
    {.id=67,         .name="Act 3 Mephisto Down L",
     .noInteract=0, .notUniqueId=TILE_ACT_3_MEPHISTO_DOWN_L},
    {.id=68,         .name="Act 3 Mephisto Down R",
     .noInteract=0, .notUniqueId=TILE_ACT_3_MEPHISTO_DOWN_R},
    {.id=69,         .name="Act 4 Mesa to Lava",
     .noInteract=0, .notUniqueId=TILE_ACT_4_MESA_TO_LAVA},
    {.id=70,         .name="Act 4 Lava to Mesa",
     .noInteract=0, .notUniqueId=TILE_ACT_4_LAVA_TO_MESA},
    {.id=71,         .name="Act 5 Barricade Down Wall L",
     .noInteract=0, .notUniqueId=TILE_ACT_5_BARRICADE_DOWN_WALL_L},
    {.id=72,         .name="Act 5 Barricade Down Wall R",
     .noInteract=0, .notUniqueId=TILE_ACT_5_BARRICADE_DOWN_WALL_R},
    {.id=73,         .name="Act 5 Barricade Down Floor",
     .noInteract=0, .notUniqueId=TILE_ACT_5_BARRICADE_DOWN_FLOOR},
    {.id=74,         .name="Act 5 Ice Caves Up L",
     .noInteract=0, .notUniqueId=TILE_ACT_5_ICE_CAVES_UP_L},
    {.id=75,         .name="Act 5 Ice Caves Up R",
     .noInteract=0, .notUniqueId=TILE_ACT_5_ICE_CAVES_UP_R},
    {.id=76,         .name="Act 5 Ice Caves Down L",
     .noInteract=0, .notUniqueId=TILE_ACT_5_ICE_CAVES_DOWN_L},
    {.id=77,         .name="Act 5 Ice Caves Down R",
     .noInteract=0, .notUniqueId=TILE_ACT_5_ICE_CAVES_DOWN_R},
    {.id=78,         .name="Act 5 Ice Caves Down Floor",
     .noInteract=0, .notUniqueId=TILE_ACT_5_ICE_CAVES_DOWN_FLOOR},
    {.id=79,         .name="Act 5 Temple Entrance",
     .noInteract=0, .notUniqueId=TILE_ACT_5_TEMPLE_ENTRANCE},
    {.id=80,         .name="Act 5 Temple Down",
     .noInteract=0, .notUniqueId=TILE_ACT_5_TEMPLE_DOWN},
    {.id=81,         .name="Act 5 Temple Up",
     .noInteract=0, .notUniqueId=TILE_ACT_5_TEMPLE_UP},
    {.id=82,         .name="Act 5 Mountain Top To Ice",
     .noInteract=1, .notUniqueId=TILE_ACT_5_MOUNTAIN_TOP_TO_ICE},
    {.id=83,         .name="Act 5 Mountain Top To Baal",
     .noInteract=1, .notUniqueId=TILE_ACT_5_MOUNTAIN_TOP_TO_BAAL},
    {.id=84,         .name="Act 5 Baal Temple Up L",
     .noInteract=0, .notUniqueId=TILE_ACT_5_BAAL_TEMPLE_UP_L},
    {.id=85,         .name="Act 5 Baal Temple Up R",
     .noInteract=0, .notUniqueId=TILE_ACT_5_BAAL_TEMPLE_UP_R},
    {.id=86,         .name="Act 5 Baal Temple Down L",
     .noInteract=0, .notUniqueId=TILE_ACT_5_BAAL_TEMPLE_DOWN_L},
    {.id=87,         .name="Act 5 Baal Temple Down R",
     .noInteract=0, .notUniqueId=TILE_ACT_5_BAAL_TEMPLE_DOWN_R}
};


const TileInfo TILE_INFO[MAX_TILE] = {
    {.id=0, .uid=UNIQUE_TILE_ACT_1_WILDERNESS_TO_CAVE_CLIFF_L},
    {.id=1, .uid=UNIQUE_TILE_ACT_1_WILDERNESS_TO_CAVE_CLIFF_R},
    {.id=2, .uid=UNIQUE_TILE_ACT_1_WILDERNESS_TO_CAVE_FLOOR_L},
    {.id=3, .uid=UNIQUE_TILE_ACT_1_WILDERNESS_TO_CAVE_FLOOR_R},
    {.id=4, .uid=UNIQUE_TILE_ACT_1_CAVE_UP},
    {.id=5, .uid=UNIQUE_TILE_ACT_1_CAVE_DOWN},
    {.id=6, .uid=UNIQUE_TILE_ACT_1_GRAVEYARD_TO_CRYPT_1},
    {.id=7, .uid=UNIQUE_TILE_ACT_1_GRAVEYARD_TO_CRYPT_2},
    {.id=8, .uid=UNIQUE_TILE_ACT_1_CRYPT_UP},
    {.id=9, .uid=UNIQUE_TILE_ACT_1_CRYPT_DOWN},
    {.id=10, .uid=UNIQUE_TILE_ACT_1_WILDERNESS_TO_TOWER},
    {.id=11, .uid=UNIQUE_TILE_ACT_1_TOWER_TO_WILDERNESS},
    {.id=12, .uid=UNIQUE_TILE_ACT_1_TOWER_TO_CRYPT},
    {.id=13, .uid=UNIQUE_TILE_ACT_1_JAIL_UP},
    {.id=14, .uid=UNIQUE_TILE_ACT_1_JAIL_DOWN},
    {.id=15, .uid=UNIQUE_TILE_ACT_1_CATHEDRAL_TO_CATACOMBS},
    {.id=16, .uid=UNIQUE_TILE_ACT_1_CATACOMBS_TO_CATHEDRAL},
    {.id=17, .uid=UNIQUE_TILE_ACT_1_CATACOMBS_UP},
    {.id=18, .uid=UNIQUE_TILE_ACT_1_CATACOMBS_DOWN},
    {.id=19, .uid=UNIQUE_TILE_ACT_2_TOWN_TO_SEWER_TRAP},
    {.id=20, .uid=UNIQUE_TILE_ACT_2_TOWN_TO_SEWER_DOCK},
    {.id=21, .uid=UNIQUE_TILE_ACT_2_SEWER_DOCK_TO_TOWN},
    {.id=22, .uid=UNIQUE_TILE_ACT_2_SEWER_UP},
    {.id=23, .uid=UNIQUE_TILE_ACT_2_SEWER_DOWN},
    {.id=24, .uid=UNIQUE_TILE_ACT_2_TOWN_TO_HAREM},
    {.id=25, .uid=UNIQUE_TILE_ACT_2_HAREM_TO_TOWN},
    {.id=26, .uid=UNIQUE_TILE_ACT_2_HAREM_UP_1},
    {.id=27, .uid=UNIQUE_TILE_ACT_2_HAREM_UP_2},
    {.id=28, .uid=UNIQUE_TILE_ACT_2_HAREM_DOWN_1},
    {.id=29, .uid=UNIQUE_TILE_ACT_2_HAREM_DOWN_2},
    {.id=30, .uid=UNIQUE_TILE_ACT_2_BASEMENT_UP_1},
    {.id=31, .uid=UNIQUE_TILE_ACT_2_BASEMENT_UP_2},
    {.id=32, .uid=UNIQUE_TILE_ACT_2_BASEMENT_DOWN},
    {.id=33, .uid=UNIQUE_TILE_ACT_2_DESERT_TO_TOMB_L_1},
    {.id=34, .uid=UNIQUE_TILE_ACT_2_DESERT_TO_TOMB_L_2},
    {.id=35, .uid=UNIQUE_TILE_ACT_2_DESERT_TO_TOMB_R_1},
    {.id=36, .uid=UNIQUE_TILE_ACT_2_DESERT_TO_TOMB_R_2},
    {.id=37, .uid=UNIQUE_TILE_ACT_2_DESERT_TO_TOMB_VIPER},
    {.id=38, .uid=UNIQUE_TILE_ACT_2_DESERT_TO_TOMB_TAL_1},
    {.id=39, .uid=UNIQUE_TILE_ACT_2_DESERT_TO_TOMB_TAL_2},
    {.id=40, .uid=UNIQUE_TILE_ACT_2_DESERT_TO_TOMB_TAL_3},
    {.id=41, .uid=UNIQUE_TILE_ACT_2_DESERT_TO_TOMB_TAL_4},
    {.id=42, .uid=UNIQUE_TILE_ACT_2_DESERT_TO_TOMB_TAL_5},
    {.id=43, .uid=UNIQUE_TILE_ACT_2_DESERT_TO_TOMB_TAL_6},
    {.id=44, .uid=UNIQUE_TILE_ACT_2_DESERT_TO_TOMB_TAL_7},
    {.id=45, .uid=UNIQUE_TILE_ACT_2_TOMB_UP},
    {.id=46, .uid=UNIQUE_TILE_ACT_2_TOMB_DOWN},
    {.id=47, .uid=UNIQUE_TILE_ACT_2_DESERT_TO_LAIR},
    {.id=48, .uid=UNIQUE_TILE_ACT_2_LAIR_UP},
    {.id=49, .uid=UNIQUE_TILE_ACT_2_LAIR_DOWN},
    {.id=50, .uid=UNIQUE_TILE_ACT_2_DESERT_TO_SEWER_TRAP},
    {.id=51, .uid=UNIQUE_TILE_ACT_3_JUNGLE_TO_SPIDER},
    {.id=52, .uid=UNIQUE_TILE_ACT_3_SPIDER_TO_JUNGLE},
    {.id=53, .uid=UNIQUE_TILE_ACT_3_JUNGLE_TO_DUNGEON_FORT},
    {.id=54, .uid=UNIQUE_TILE_ACT_3_JUNGLE_TO_DUNGEON_HOLE},
    {.id=55, .uid=UNIQUE_TILE_ACT_3_DUNGEON_UP},
    {.id=56, .uid=UNIQUE_TILE_ACT_3_DUNGEON_DOWN},
    {.id=57, .uid=UNIQUE_TILE_ACT_3_KURAST_TO_SEWER},
    {.id=58, .uid=UNIQUE_TILE_ACT_3_SEWER_UP_L},
    {.id=59, .uid=UNIQUE_TILE_ACT_3_SEWER_UP_R},
    {.id=60, .uid=UNIQUE_TILE_ACT_3_SEWER_DOWN},
    {.id=61, .uid=UNIQUE_TILE_ACT_3_KURAST_TO_TEMPLE},
    {.id=62, .uid=UNIQUE_TILE_ACT_3_TEMPLE_UP_L},
    {.id=63, .uid=UNIQUE_TILE_ACT_3_TEMPLE_UP_R},
    {.id=64, .uid=UNIQUE_TILE_ACT_3_TRAVINCAL_TO_MEPHISTO},
    {.id=65, .uid=UNIQUE_TILE_ACT_3_MEPHISTO_UP_L},
    {.id=66, .uid=UNIQUE_TILE_ACT_3_MEPHISTO_UP_R},
    {.id=67, .uid=UNIQUE_TILE_ACT_3_MEPHISTO_DOWN_L},
    {.id=68, .uid=UNIQUE_TILE_ACT_3_MEPHISTO_DOWN_R},
    {.id=69, .uid=UNIQUE_TILE_ACT_4_MESA_TO_LAVA},
    {.id=70, .uid=UNIQUE_TILE_ACT_4_LAVA_TO_MESA},
    {.id=71, .uid=UNIQUE_TILE_ACT_5_BARRICADE_DOWN_WALL_L},
    {.id=72, .uid=UNIQUE_TILE_ACT_5_BARRICADE_DOWN_FLOOR},
    {.id=73, .uid=UNIQUE_TILE_ACT_5_ICE_CAVES_UP_L},
    {.id=74, .uid=UNIQUE_TILE_ACT_5_ICE_CAVES_DOWN_L},
    {.id=75, .uid=UNIQUE_TILE_ACT_5_ICE_CAVES_DOWN_FLOOR},
    {.id=76, .uid=UNIQUE_TILE_ACT_5_TEMPLE_ENTRANCE},
    {.id=77, .uid=UNIQUE_TILE_ACT_5_TEMPLE_DOWN},
    {.id=78, .uid=UNIQUE_TILE_ACT_5_TEMPLE_UP},
    {.id=79, .uid=UNIQUE_TILE_ACT_5_MOUNTAIN_TOP_TO_ICE},
    {.id=80, .uid=UNIQUE_TILE_ACT_5_MOUNTAIN_TOP_TO_BAAL},
    {.id=81, .uid=UNIQUE_TILE_ACT_5_BAAL_TEMPLE_UP_L},
    {.id=82, .uid=UNIQUE_TILE_ACT_5_BAAL_TEMPLE_DOWN_L}
};
